baseURL = "http://blog.matthewlawrencekle.in/"
languageCode = "en-us"
title = "Matthew Lawrence Klein - A Personal Blog"
theme = 'yinyang-fork'
publish = './docs'

[author]
    name = 'Matthew Lawrence Klein'
    homepage = 'http://matthewlawrencekle.in'


[params]
    mainSections = ['posts']
    headTitle = "Matthew Lawrence Klein blog / thought hole"
[[params.socials]]
    name = "About"
    link = "http://matthewlawrencekle.in"
[[params.socials]]
    name = "Github"
    link = "https://github.com/matthewlawrenceklein"
